[platformio]
default_envs = m5stack-cores3

[env:m5stack-cores3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
build_flags =
    -DARDUINO_M5STACK_CORES3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX@>=0.2.27
    bblanchon/ArduinoJson@^7.0.0
    ricmoo/QRCode@^0.0.1
